# Labeler Configuration
area: project-management:
  - backlog/**/*
  - docs/departments/project_management/**/*

area: engineering:
  - src/**/*
  - packages/**/*
  - cloudbuild.yaml

area: infrastructure:
  - terraform/**/*
  - tools/**/*

area: governance:
  - backlog/STRATEGY.md
  - backlog/GOVERNANCE.md
