steps:
  # 1. Install Dependencies & Build Skills
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--prefix', 'packages/google-native-skills']
    id: 'install-skills'

  # 2. Test Skills (Unit Tests)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['test', '--prefix', 'packages/google-native-skills']
    id: 'test-skills'
    # Allow failure for now to keep velocity high (as requested)
    # allow_failure: true

  # 3. Terraform Init
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init

  # 4. Terraform Plan (Validation)
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform plan -out=tfplan

  # 5. Terraform Apply (Auto-Deploy)
  # Only runs on main branch
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform apply -auto-approve tfplan

timeout: '1200s' # 20 minutes
options:
  logging: CLOUD_LOGGING_ONLY
