import os
import sys
import argparse
import json

def scaffold_department(name, dept_type):
    safe_name = name.lower().replace(" ", "-")
    print(f"🏗️ The Architect is building: {name} ({dept_type})...")

    tf_dir = f"terraform/modules/{safe_name}"
    os.makedirs(tf_dir, exist_ok=True)

    with open(f"{tf_dir}/main.tf", "w") as f:
        f.write(f"""# Department: {name}
# Type: {dept_type}
# Generated by The Architect

resource "google_compute_instance" "agent_node" {{
  name         = "{safe_name}-agent"
  machine_type = "e2-medium"
  zone         = var.zone

  boot_disk {{
    initialize_params {{
      image = "debian-cloud/debian-11"
    }}
  }}

  network_interface {{
    network = var.vpc_id
  }}
}}
""")

    with open(f"{tf_dir}/variables.tf", "w") as f:
        f.write('variable "zone" {}\nvariable "vpc_id" {}\n')

    print(f"  - Infrastructure: {tf_dir}/main.tf")

    persona_file = f"src/knowledge/personas/{safe_name}.json"
    persona_data = {
        "name": name,
        "role": dept_type,
        "prime_directive": "Efficiency",
        "commandments_adherence": "Strict",
        "description": f"The AI agent responsible for {name} operations."
    }

    with open(persona_file, "w") as f:
        json.dump(persona_data, f, indent=2)

    print(f"  - Persona: {persona_file}")

    registry_file = "src/knowledge/projects/registry.json"
    if os.path.exists(registry_file):
        with open(registry_file, "r") as f:
            registry = json.load(f)

        new_project = {
            "id": f"PROJ-{len(registry.get('projects', [])) + 1:03d}",
            "name": name,
            "description": f"Operational unit for {dept_type}.",
            "owner": safe_name,
            "status": "INIT"
        }

        registry["projects"].append(new_project)

        with open(registry_file, "w") as f:
            json.dump(registry, f, indent=2)

        print(f"  - Registry: Added {new_project['id']}")

    print(f"✅ Scaffold Complete. {name} is ready for habitation.")

def main():
    parser = argparse.ArgumentParser(description="Scaffold a new Department.")
    parser.add_argument("--name", required=True, help="Name of the department")
    parser.add_argument("--type", required=True, help="Type/Role (e.g., Security, Logistics)")

    args = parser.parse_args()
    scaffold_department(args.name, args.type)

if __name__ == "__main__":
    main()
