openapi: 3.0.0
info:
  title: OpenClaw PMO Event API
  version: 1.0.0
  description: Event-Driven Interface for the Project Management Office (Pub/Sub).

components:
  schemas:
    # INPUT: Task Creation
    TaskCreatedEvent:
      type: object
      required: [id, title, priority, type, description]
      properties:
        id:
          type: string
          description: Unique Message ID (UUID)
        source:
          type: string
          description: Origin system (e.g., "slack-bot", "email-gateway")
        timestamp:
          type: string
          format: date-time
        title:
          type: string
        priority:
          type: string
          enum: [Critical, High, Medium, Low]
        type:
          type: string
          enum: [Feature, Bug, Architecture, Security, Hotfix]
        prime_directive:
          type: string
          description: Alignment (Optional, inferred if missing)
        description:
          type: string
          description: Markdown content

    # OUTPUT: Status Report
    StatusPublishedEvent:
      type: object
      required: [date, velocity, active_count, risks, report_url]
      properties:
        date:
          type: string
          format: date
        velocity:
          type: number
        active_count:
          type: integer
        risks:
          type: array
          items:
            type: string
        report_url:
          type: string
          description: URL to the raw STATUS.md file

channels:
  pmo-inbox-input:
    description: The Global Queue for new tasks.
    subscribe:
      message:
        $ref: '#/components/schemas/TaskCreatedEvent'

  pmo-status-output:
    description: The Daily State of the Union broadcast.
    publish:
      message:
        $ref: '#/components/schemas/StatusPublishedEvent'
